# Generated by Django 3.1.2 on 2020-10-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Climbig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Other_Activities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Runs_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Specific_Location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(max_length=100),
        ),
    ]
