# Generated by Django 3.1.2 on 2020-10-17 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20201017_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Longtitude',
            new_name='Longitude',
        ),
    ]
