# Generated by Django 3.1.2 on 2020-10-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0005_auto_20201017_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
