# Generated by Django 3.1.2 on 2020-10-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0006_auto_20201017_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Climbig',
            new_name='Climbing',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
