# Generated by Django 3.1.2 on 2020-10-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0007_auto_20201017_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=100, null=True),
        ),
    ]
